# Generated by Django 5.2.8 on 2025-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_twofactorsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="twofactorcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "多因子驗證碼",
                "verbose_name_plural": "多因子驗證碼",
            },
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="code",
            field=models.CharField(
                help_text="6-digit numeric verification code",
                max_length=6,
                verbose_name="驗證碼",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when code was generated",
                verbose_name="建立日期",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="Timestamp when code expires",
                verbose_name="到期日期",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="failed_attempts",
            field=models.IntegerField(
                default=0,
                help_text="Number of failed verification attempts for this code",
                verbose_name="失敗驗證次數",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="Whether code has been used successfully",
                verbose_name="是否已使用",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorcode",
            name="verification_type",
            field=models.CharField(
                choices=[("TWO_FACTOR", "Two-Factor Authentication")],
                default="TWO_FACTOR",
                help_text="Type of verification this code is used for",
                max_length=20,
                verbose_name="驗證類型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立日期"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with this email already exists."},
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether user email has been verified",
                verbose_name="Email 驗證",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google OAuth user ID",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has enabled two-factor authentication",
                verbose_name="是否啟用兩步驟驗證",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_2fa_verification",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last successful 2FA verification for audit trails",
                null=True,
                verbose_name="最後兩步驟驗證日期",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in international format (e.g., +1 234 5678901)",
                max_length=17,
                null=True,
                verbose_name="手機號碼",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether user phone number has been verified for 2FA",
                verbose_name="手機號碼驗證",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_2fa_method",
            field=models.CharField(
                blank=True,
                choices=[("EMAIL", "Email"), ("PHONE", "Phone")],
                help_text="User preferred 2FA method (null uses system default)",
                max_length=20,
                null=True,
                verbose_name="偏好兩步驟驗證方式",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                help_text="URL to user profile picture from OAuth provider",
                null=True,
                verbose_name="大頭貼網址",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="twofa_setup_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user first enabled 2FA",
                null=True,
                verbose_name="兩步驟驗證設定日期",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日期"),
        ),
    ]
