# Generated by Django 5.2.8 on 2025-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_twofactorcode_options_alter_twofactorcode_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "系統超級管理員"),
                    ("ADMIN", "系統管理員"),
                    ("CLINIC_ADMIN", "診所管理員"),
                    ("CLINIC_STAFF", "診所員工"),
                    ("CLIENT", "客戶"),
                ],
                default="CLIENT",
                help_text="User role for permission management",
                max_length=20,
                verbose_name="權限角色",
            ),
        ),
    ]
