# Generated by Django 5.2.8 on 2025-12-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
    ]
