# Generated by Django 5.2.8 on 2025-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="information_source",
            field=models.CharField(
                choices=[
                    ("friends_family", "親友推薦"),
                    ("social_media", "社群媒體"),
                    ("internet_search", "網路搜尋"),
                    ("other", "其他"),
                ],
                default=1,
                help_text="怎麼知道LBV認證活動資訊",
                max_length=20,
                verbose_name="資訊來源",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="occupation_category",
            field=models.CharField(
                choices=[
                    ("doctor", "醫師"),
                    ("nurse", "護理師"),
                    ("consultant", "諮詢師"),
                    ("administrator", "行政人員"),
                    ("other", "其他"),
                ],
                default="other",
                help_text="申請人的職業類別",
                max_length=20,
                verbose_name="職業類別",
            ),
        ),
    ]
