# Generated by Django 5.2.8 on 2025-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_cert_record_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="要驗證的 email 地址",
                        max_length=254,
                        verbose_name="Email 地址",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6 位數驗證碼", max_length=6, verbose_name="驗證碼"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="驗證碼生成時間",
                        verbose_name="建立時間",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="驗證碼過期時間",
                        verbose_name="過期時間",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="驗證碼是否已被使用",
                        verbose_name="是否已使用",
                    ),
                ),
                (
                    "failed_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="失敗驗證次數（超過 5 次需重新發送）",
                        verbose_name="失敗驗證次數",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email 驗證 OTP",
                "verbose_name_plural": "Email 驗證 OTP",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "is_used"], name="users_email_email_e5437e_idx"
                    ),
                    models.Index(
                        fields=["email", "expires_at"],
                        name="users_email_email_68d6a7_idx",
                    ),
                ],
            },
        ),
    ]
