# Generated by Django 5.2.8 on 2025-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_emailverificationotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="用戶生日", null=True, verbose_name="生日"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男性"), ("female", "女性"), ("other", "其他")],
                help_text="用戶性別",
                max_length=10,
                null=True,
                verbose_name="性別",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy_accepted",
            field=models.BooleanField(
                default=False,
                help_text="用戶是否同意隱私權條款",
                verbose_name="是否同意隱私權條款",
            ),
        ),
    ]
