# Generated by Django 5.2.8 on 2026-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_birth_date_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="occupation_category_custom",
            field=models.CharField(
                blank=True,
                help_text="當選擇「其他（請填寫）」時，可在此填寫自定義職業類別",
                max_length=100,
                null=True,
                verbose_name="自定義職業類別",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupation_category",
            field=models.CharField(
                choices=[
                    ("admin_office", "行政／白領辦公"),
                    ("education", "教育／學術／培訓"),
                    ("medical", "醫療／護理／醫技"),
                    ("finance", "金融／會計／稅務"),
                    ("legal", "法律／專業顧問"),
                    ("tech", "科技／工程／資訊"),
                    ("marketing", "行銷／廣告／媒體"),
                    ("sales", "業務／銷售"),
                    ("service", "服務業／餐飲／零售"),
                    ("design", "設計／藝術／創意產業"),
                    ("manufacturing", "製造業／工業技術／工廠"),
                    ("agriculture", "農林漁牧／戶外工作"),
                    ("transport", "交通運輸／物流"),
                    ("self_employed", "自營商／自由工作者"),
                    ("homemaker", "家庭主婦／全職家長"),
                    ("student", "學生"),
                    ("retired", "退休"),
                    ("custom", "其他（請填寫）"),
                    ("other", "其他"),
                ],
                default="other",
                help_text="申請人的職業類別",
                max_length=50,
                verbose_name="職業類別",
            ),
        ),
    ]
