# Generated by Django 5.2.8 on 2026-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_occupation_category_custom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has enabled two-factor authentication",
                verbose_name="是否啟用兩步驟驗證",
            ),
        ),
    ]
