# Generated by Django 5.2.8 on 2026-01-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_user_is_2fa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="residence_county",
            field=models.CharField(
                blank=True,
                help_text="用戶居住地縣市",
                max_length=20,
                null=True,
                verbose_name="居住地縣市",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="information_source",
            field=models.CharField(
                choices=[
                    ("friends_family", "親友推薦"),
                    ("social_media", "社群媒體"),
                    ("internet_search", "網路搜尋"),
                    ("famous", "名人推薦"),
                    ("other", "其他"),
                ],
                help_text="怎麼知道LBV認證活動資訊",
                max_length=20,
                verbose_name="資訊來源",
            ),
        ),
    ]
