# Generated by Django 5.2.8 on 2026-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_residence_county_alter_user_information_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "此電子郵件已被使用。"},
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                error_messages={"invalid": "無效的 Email 驗證狀態。"},
                help_text="Whether user email has been verified",
                verbose_name="Email 驗證",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                error_messages={"unique": "此 Google ID 已被使用。"},
                help_text="Google OAuth user ID",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                error_messages={"invalid": "無效的兩步驟驗證狀態。"},
                help_text="Whether user has enabled two-factor authentication",
                verbose_name="是否啟用兩步驟驗證",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                error_messages={
                    "invalid": "無效的手機號碼格式。",
                    "max_length": "手機號碼長度不能超過 {max_length} 個字元。",
                },
                help_text="Phone number in international format (e.g., +1 234 5678901)",
                max_length=17,
                null=True,
                unique=True,
                verbose_name="手機號碼",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "無效的大頭貼網址格式。"},
                help_text="URL to user profile picture from OAuth provider",
                null=True,
                verbose_name="大頭貼網址",
            ),
        ),
    ]
