# Generated by Django 5.2.8 on 2025-12-03 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="active_end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="失效時間"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="active_member",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="發布人"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="active_start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="生效時間"),
        ),
    ]
