# Generated by Django 5.2.8 on 2025-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0003_announcement_email_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="是否發布"),
        ),
    ]
