# Generated by Django 5.2.8 on 2025-12-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinic_number_alter_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='consultant_name',
            field=models.CharField(blank=True, help_text='諮詢師姓名', max_length=255, null=True, verbose_name='諮詢師'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='consultation_clinic',
            field=models.ForeignKey(blank=True, help_text='諮詢診所', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_certificate_applications', to='clinic.clinic', verbose_name='諮詢診所'),
        ),
        migrations.AddField(
            model_name='certificateapplication',
            name='surgeon_name',
            field=models.CharField(blank=True, help_text='手術醫師姓名', max_length=255, null=True, verbose_name='手術醫師'),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='clinic',
            field=models.ForeignKey(help_text='證書所屬的診所（主要診所）', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_applications', to='clinic.clinic', verbose_name='診所'),
        ),
    ]
