# Generated by Django 5.2.8 on 2026-01-22 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_certificateapplication_certificate_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="number",
            field=models.CharField(
                help_text="門市名稱", max_length=255, verbose_name="門市名稱"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.UniqueConstraint(
                fields=("name", "number"), name="unique_clinic_name_number"
            ),
        ),
    ]
