# Generated by Django 5.2.8 on 2026-01-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新時間"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Task Name")),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
                (
                    "period",
                    models.CharField(
                        help_text="Cron expression",
                        max_length=100,
                        verbose_name="Cron Period",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                ("contents", models.JSONField(default=list, verbose_name="Contents")),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_ownership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        related_name="notification_tasks_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Targets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Task",
                "verbose_name_plural": "Notification Tasks",
            },
        ),
    ]
