# Generated by Django 5.2.8 on 2026-01-21 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtask",
            name="roles",
            field=models.JSONField(blank=True, default=list, verbose_name="Roles"),
        ),
        migrations.AlterField(
            model_name="notificationtask",
            name="targets",
            field=models.ManyToManyField(
                blank=True,
                related_name="notification_tasks_targets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Targets",
            ),
        ),
    ]
